spring:
  application:
    name: item-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
---
spring:
  profiles: item1
  rabbitmq:
    host: 192.168.110.130
    port: 5672
    username: admin
    password: admin
  
server:
  port: 8001
---
spring:
  profiles: item2
  rabbitmq:
    host: 192.168.110.130
    port: 5672
    username: admin
    password: admin

server:
  port: 8002

